# Generated by Django 3.0.6 on 2020-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
